language: r
r:
- release
- devel
sudo: false
cache: packages
addons:
  apt:
    packages:
    - xclip
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: eEKXAlC0xGLwKGrRnrvshPyLnPPCTfMCA2EPGCldxZ6+JC23KWnj+Z7q63AuyKIa7ndKiOr1C2BOeXBD6oSOx+ESiLMLJ1ONE2O0Fupf9xn3jkSAb4NmtT8wP64Gga+Pq0NBaMEgGG1E99BRta/nssz6UKjKHbZ/52Iap9xPwoo=
